config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resource :session, only: [:new, :create, :destroy]
  get '/signin', to: "sessions#new"
  resources :users
  get '/signup', to: "users#new"
  get 'movies/filter/:filter', to: "movies#index", as: "filtered_movies"
  root "movies#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies do
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug

  validates :name, presence: true, uniqueness: true
  has_many :characterizations
  has_many :movies, through: :characterizations



  def to_param
    slug
  end

  private 

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin
  before_action :require_admin
  before_action :set_genre
  
  def index 
    @genres = Genre.all
  end

  def show 
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create 
    @genre = Genre.new(params_genre)
    if @genre.save
      redirect_to genres_path
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if @genre.update(params_genre)
      redirect_to @genre
    else
      render :edit
    end
  end

  def destroy
    if @genre.destroy 
      redirect_to genres_path
    end
  end

  private 

  def set_genre
    @genre = Genre.find_by! slug: params[:id]
  end

  def params_genre
    params.require(:genre).permit!
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with model: genre, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/genres/index.html.erb
<h1>Genres </h1>
<% @genres.each do |genre| %>
  <%= link_to genre.name, genre %>
  <%= time_ago_in_words genre.created_at %>
<% end %>

<section>
  <%= link_to 'Add more genres', new_genre_path %>
</section>

app/views/genres/new.html.erb
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>
<% @movies.each do |movie| %>
  <%= link_to movie.title, movie_path(movie) %>
<% end %>