config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resource :session, only: [:new, :create, :destroy]
  get '/signin', to: "sessions#new"
  resources :users
  get '/signup', to: "users#new"
  get 'movies/filter/:filter', to: "movies#index", as: "filtered_movies"
  root "movies#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies do
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "flash #{type}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright by Camille-Code <%= Time.now.year %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag('logo.png'), root_path %>
    <ul class="left">
      <li><%= nav_link_to "Released", movies_path %></li>
      <li><%= nav_link_to 'Upcoming', filtered_movies_path("upcoming") %></li>
      <li><%= nav_link_to 'Recent', filtered_movies_path("recent") %></li>
      <li><%= nav_link_to 'Hits', filtered_movies_path("hits") %></li>
      <li><%= nav_link_to 'Flops', filtered_movies_path("flops") %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to "Sign Out", session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", signup_path, class: "button" %> </li>
        <li><%= link_to "Sign in", signin_path, class: "button" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= render 'layouts/flash' %>
    </div>
    <div class="content">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>